language: generic
sudo: required
services:
    - docker

before_install:
    - docker build -t nb2099/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true nb2099/docker-react npm run test